name: Use secret as input
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use secret in a script
        run: |
          echo "Using secret..."
          echo "Secret value is: ${{ secrets.ProjectDokumentation }}"
